plugin: aws_ec2
regions:
  - us-west-2  # Change this to your preferred region
filters:
  tag:Name: example-instance  # Ensure this matches the tag used in your Terraform configuration
hostnames:
  - private-ip-address
compose:
  ansible_host: public-ip-address
